version: "3"
networks:
  origo-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.1/24

services:
  origo:
    container_name: origo
    image: rrooliveira/origo
    restart: always
    ports:
      - "8083:8083"
    networks:
      - origo-network
    volumes:
      - ./:/var/www/html
    tty: true

  mysql:
    container_name: origo-db
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    tty: true
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      - MYSQL_DATABASE=origo
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - origo-network